services:
  # Database Service
  - type: pserv
    name: todo-database
    env: docker
    plan: free
    databases:
      - name: todoapp
        databaseName: todoapp
        user: todouser

  # Backend Service
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    buildCommand: echo "Building backend..."
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-database
          property: connectionString
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /health

  # Frontend Service  
  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    buildCommand: echo "Building frontend..."
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: be-todo
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: todo-database
    databaseName: todoapp
    user: todouser
    plan: free