name: Secure Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
  STUDENT_ID: "02230307"  # Your student ID

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./to-do
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ env.DOCKER_HUB_REPO }}/be-todo-secure:${{ env.STUDENT_ID }}
        platforms: linux/amd64
    
    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: ${{ env.DOCKER_HUB_REPO }}/fe-todo-secure:${{ env.STUDENT_ID }}
        platforms: linux/amd64
    
    - name: Image digest
      run: |
        echo "Backend image: ${{ env.DOCKER_HUB_REPO }}/be-todo-secure:${{ env.STUDENT_ID }}"
        echo "Frontend image: ${{ env.DOCKER_HUB_REPO }}/fe-todo-secure:${{ env.STUDENT_ID }}"